
package fr.polytech;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CliService", targetNamespace = "http://www.polytech.fr", wsdlLocation = "file:/C:/Users/theom/Documents/JEE/Client/src/CliService.wsdl")
public class CliService
    extends Service
{

    private final static URL CLISERVICE_WSDL_LOCATION;
    private final static WebServiceException CLISERVICE_EXCEPTION;
    private final static QName CLISERVICE_QNAME = new QName("http://www.polytech.fr", "CliService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/theom/Documents/JEE/Client/src/CliService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLISERVICE_WSDL_LOCATION = url;
        CLISERVICE_EXCEPTION = e;
    }

    public CliService() {
        super(__getWsdlLocation(), CLISERVICE_QNAME);
    }

    public CliService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLISERVICE_QNAME, features);
    }

    public CliService(URL wsdlLocation) {
        super(wsdlLocation, CLISERVICE_QNAME);
    }

    public CliService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLISERVICE_QNAME, features);
    }

    public CliService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CliService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Cli
     */
    @WebEndpoint(name = "CliPort")
    public Cli getCliPort() {
        return super.getPort(new QName("http://www.polytech.fr", "CliPort"), Cli.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Cli
     */
    @WebEndpoint(name = "CliPort")
    public Cli getCliPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytech.fr", "CliPort"), Cli.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLISERVICE_EXCEPTION!= null) {
            throw CLISERVICE_EXCEPTION;
        }
        return CLISERVICE_WSDL_LOCATION;
    }

}
