
package fr.polytech;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Ter", targetNamespace = "http://www.polytech.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Ter {


    /**
     * 
     * @return
     *     returns java.util.List<fr.polytech.Terrain>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "afficher", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.Afficher")
    @ResponseWrapper(localName = "afficherResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.AfficherResponse")
    @Action(input = "http://www.polytech.fr/Ter/afficherRequest", output = "http://www.polytech.fr/Ter/afficherResponse")
    public List<Terrain> afficher();

}
