
package fr.polytech;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TerService", targetNamespace = "http://www.polytech.fr", wsdlLocation = "file:/C:/Users/theom/Documents/JEE/Client/src/TerService.wsdl")
public class TerService
    extends Service
{

    private final static URL TERSERVICE_WSDL_LOCATION;
    private final static WebServiceException TERSERVICE_EXCEPTION;
    private final static QName TERSERVICE_QNAME = new QName("http://www.polytech.fr", "TerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/theom/Documents/JEE/Client/src/TerService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TERSERVICE_WSDL_LOCATION = url;
        TERSERVICE_EXCEPTION = e;
    }

    public TerService() {
        super(__getWsdlLocation(), TERSERVICE_QNAME);
    }

    public TerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TERSERVICE_QNAME, features);
    }

    public TerService(URL wsdlLocation) {
        super(wsdlLocation, TERSERVICE_QNAME);
    }

    public TerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TERSERVICE_QNAME, features);
    }

    public TerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Ter
     */
    @WebEndpoint(name = "TerPort")
    public Ter getTerPort() {
        return super.getPort(new QName("http://www.polytech.fr", "TerPort"), Ter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ter
     */
    @WebEndpoint(name = "TerPort")
    public Ter getTerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytech.fr", "TerPort"), Ter.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TERSERVICE_EXCEPTION!= null) {
            throw TERSERVICE_EXCEPTION;
        }
        return TERSERVICE_WSDL_LOCATION;
    }

}
