
package fr.polytech;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Cli", targetNamespace = "http://www.polytech.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Cli {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hashPasswordClient", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.HashPasswordClient")
    @ResponseWrapper(localName = "hashPasswordClientResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.HashPasswordClientResponse")
    @Action(input = "http://www.polytech.fr/Cli/hashPasswordClientRequest", output = "http://www.polytech.fr/Cli/hashPasswordClientResponse")
    public String hashPasswordClient(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "ajouterClient", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.AjouterClient")
    @ResponseWrapper(localName = "ajouterClientResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.AjouterClientResponse")
    @Action(input = "http://www.polytech.fr/Cli/ajouterClientRequest", output = "http://www.polytech.fr/Cli/ajouterClientResponse")
    public void ajouterClient(
        @WebParam(name = "arg0", targetNamespace = "")
        Client arg0);

    /**
     * 
     * @return
     *     returns java.util.List<fr.polytech.Client>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "afficherClient", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.AfficherClient")
    @ResponseWrapper(localName = "afficherClientResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.AfficherClientResponse")
    @Action(input = "http://www.polytech.fr/Cli/afficherClientRequest", output = "http://www.polytech.fr/Cli/afficherClientResponse")
    public List<Client> afficherClient();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "seConnecterClient", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.SeConnecterClient")
    @ResponseWrapper(localName = "seConnecterClientResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.SeConnecterClientResponse")
    @Action(input = "http://www.polytech.fr/Cli/seConnecterClientRequest", output = "http://www.polytech.fr/Cli/seConnecterClientResponse")
    public void seConnecterClient();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logClient", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.LogClient")
    @ResponseWrapper(localName = "logClientResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.LogClientResponse")
    @Action(input = "http://www.polytech.fr/Cli/logClientRequest", output = "http://www.polytech.fr/Cli/logClientResponse")
    public boolean logClient(
        @WebParam(name = "arg0", targetNamespace = "")
        Client arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "existClient", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.ExistClient")
    @ResponseWrapper(localName = "existClientResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.ExistClientResponse")
    @Action(input = "http://www.polytech.fr/Cli/existClientRequest", output = "http://www.polytech.fr/Cli/existClientResponse")
    public boolean existClient(
        @WebParam(name = "arg0", targetNamespace = "")
        Client arg0);

}
