
package fr.polytech;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Ter", targetNamespace = "http://www.polytech.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Ter {


    /**
     * 
     * @return
     *     returns java.util.List<fr.polytech.Terrain>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "afficherTerrain", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.AfficherTerrain")
    @ResponseWrapper(localName = "afficherTerrainResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.AfficherTerrainResponse")
    @Action(input = "http://www.polytech.fr/Ter/afficherTerrainRequest", output = "http://www.polytech.fr/Ter/afficherTerrainResponse")
    public List<Terrain> afficherTerrain();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "supprimerTerrain", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.SupprimerTerrain")
    @ResponseWrapper(localName = "supprimerTerrainResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.SupprimerTerrainResponse")
    @Action(input = "http://www.polytech.fr/Ter/supprimerTerrainRequest", output = "http://www.polytech.fr/Ter/supprimerTerrainResponse")
    public void supprimerTerrain(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "seConnecterTerrain", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.SeConnecterTerrain")
    @ResponseWrapper(localName = "seConnecterTerrainResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.SeConnecterTerrainResponse")
    @Action(input = "http://www.polytech.fr/Ter/seConnecterTerrainRequest", output = "http://www.polytech.fr/Ter/seConnecterTerrainResponse")
    public void seConnecterTerrain();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "ajouterTerrain", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.AjouterTerrain")
    @ResponseWrapper(localName = "ajouterTerrainResponse", targetNamespace = "http://www.polytech.fr", className = "fr.polytech.AjouterTerrainResponse")
    @Action(input = "http://www.polytech.fr/Ter/ajouterTerrainRequest", output = "http://www.polytech.fr/Ter/ajouterTerrainResponse")
    public void ajouterTerrain(
        @WebParam(name = "arg0", targetNamespace = "")
        Terrain arg0);

}
